import styles from "@/styles/layout/Footer.module.scss";
import Container from "./Container";
import Logo from "./Logo";
import Link from "next/link";

export default function Footer() {
  const footerLinks = [
    { href: "/#home", text: "Home" },
    { href: "/#what-is-it", text: "What's it" },
    { href: "/#alter-ego", text: "Alter Ego" },
    { href: "/#inspirations", text: "Inspirations" },
  ];

  return (
    <footer className={styles.footer}>
      <Container>
        <div className={styles.footer_container}>
          <div className={styles.footer_logo}>
            <Logo />
          </div>
          <nav className={styles.footer_links}>
            {footerLinks.map((link) => (
              <Link href={link.href} key={link.href}>
                {link.text}
              </Link>
            ))}
          </nav>
          <div className={styles.footer_rights}>
            <p>All images was generated by IA</p>
          </div>
        </div>
      </Container>
    </footer>
  );
}
