import type { Metadata } from "next";
import { UnifrakturCook, Exo_2 } from "next/font/google";
import "./globals.scss";
import MainContainer from "@/components/layout/MainContainer";
import NavbarProvider from "@/_context/NavbarContext";

const unifracturCook = UnifrakturCook({
  variable: "--font-cook",
  weight: ["700"],
  subsets: ["latin"],
});

const exo_2 = Exo_2({
  variable: "--font-exo2",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Alter Ego",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo_2.className} ${unifracturCook.variable}`}
      >
        <NavbarProvider>
          <MainContainer>{children}</MainContainer>
        </NavbarProvider>
      </body>
    </html>
  );
}
